InvoiceManager/Models/Domains/Client.cs
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace InvoiceManager.Models.Domains
{
    public class Client
    {
        public Client()
        {
            Invoices = new Collection<Invoice>();
        }

        public int Id { get; set; }

        [Required]
        [Display(Name="Nabywca")]
        public string Name { get; set; }
        public int AddressId { get; set; }

        [Required]
        public string Email { get; set; }

        [Required]
        [ForeignKey("User")]
        public string UserId { get; set; }


        public Address Address { get; set; }
        public ICollection<Invoice> Invoices { get; set; }

        public ApplicationUser User { get; set; }

    }
}

InvoiceManager/Models/Domains/Invoice.cs
using InvoiceManager.Models.Domains;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace InvoiceManager.Models.Domains
{
    public class Invoice
    {
        public Invoice()
        {
            InvoicePositions = new Collection<InvoicePosition>();
        }
        public int Id { get; set; }

        [Required(ErrorMessage = "Pole Tytuł jest wymagane")]
        [Display(Name = "Tytuł")]
        public string Title { get; set; }

        [DisplayFormat(DataFormatString = "{0:C}")]
        [Display(Name = "Wartość netto")]
        public decimal NetValue { get; set; }

        [DisplayFormat(DataFormatString = "{0:C}")]
        [Display(Name = "Wartość brutto")]
        public decimal GrossValue { get; set; }

        [Required(ErrorMessage = "Pole Sposób płatności jest wymagane")]
        [Display(Name = "Sposób płatności")]
        public int MethodOfPaymentId { get; set; }

        [Required(ErrorMessage = "Pole Data płatności jest wymagane")]
        [Display(Name = "Data płatności")]
        public DateTime PaymentDate { get; set; }

        [Display(Name = "Data utworzenia")]
        public DateTime CreatedDate { get; set; }

        [Display(Name = "Uwagi")]
        public string Comments { get; set; }

        [Required(ErrorMessage = "Pole Klient jest wymagane")]
        [Display(Name = "Klient")]
        public int ClientId { get; set; }

        [Required]
        [ForeignKey("User")]
        public string UserId { get; set; }

        
        public MethodofPayment MethodofPayment { get; set; }
        public Client Client { get; set; }
        public ApplicationUser User { get; set; }
        public ICollection<InvoicePosition> InvoicePositions { get; set; }
    }
}

InvoiceManager/Models/Domains/InvoicePosition.cs
using System.ComponentModel.DataAnnotations;

namespace InvoiceManager.Models.Domains
{
    public class InvoicePosition
    {
        public int Id { get; set; }
        public int InvoiceId { get; set; }

        [Required]
        [DisplayFormat(DataFormatString = "{0:N}", ApplyFormatInEditMode = true)]
        public decimal NetValue { get; set; }

        [Required]
        [DisplayFormat(DataFormatString = "{0:N}", ApplyFormatInEditMode = true)]
        public decimal VatValue { get; set; }

        [Required(ErrorMessage = "Pole Produkt jest wymagane")]
        [Display(Name = "Produkt")]
        public int ProductId { get; set; }

        [Required(ErrorMessage = "Pole Ilość jest wymagane")]
        [Display(Name = "Ilość")]
        public int Quantity { get; set; }

        [Required(ErrorMessage = "Pole Jednostka miary jest wymagane")]
        [Display(Name = "Jednostka miary")]
        public int UnitofMeasureId { get; set; }

        public Invoice Invoice { get; set; }
        public Product Product { get; set; }
        public UnitofMeasure UnitofMeasure { get; set; }
    }
}

InvoiceManager/Models/Domains/Product.cs
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace InvoiceManager.Models.Domains
{
    public class Product
    {
        public Product()
        {
            InvoicePositions = new Collection<InvoicePosition>();
                        
        }

        public int Id { get; set; }

        [Display(Name = "Nazwa produktu")]
        [Required]
        public string Name { get; set; }

        [Display(Name = "Cena Netto")]
        [DisplayFormat(DataFormatString = "{0:N}", ApplyFormatInEditMode = true)]
        public decimal NetPrice { get; set; }

        [Display(Name = "Stawka Vat %")]
        public int VatRate { get; set; }

        [Display(Name = "Kwota VAT")]
        [DisplayFormat(DataFormatString = "{0:N}", ApplyFormatInEditMode = true)]
        public decimal VatAmount { get; set; }

        [Display(Name = "Cena Brutto")]
        [DisplayFormat(DataFormatString = "{0:N}", ApplyFormatInEditMode = true)]
        public decimal GrossPrice { get; set; }


        [Required]
        [ForeignKey("User")]
        public string UserId { get; set; }





        public ApplicationUser User { get; set; }
        public ICollection<InvoicePosition> InvoicePositions { get; set; }
    }
}

InvoiceManager/Controllers/HomeController.cs
using InvoiceManager.Models;
using InvoiceManager.Models.Domains;
using InvoiceManager.Models.Repositories;
using InvoiceManager.Models.ViewModels;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace InvoiceManager.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {

        private InvoiceRepository _invoiceRepository = new InvoiceRepository();
        private ClientRepository _clientRepository = new ClientRepository();
        private ProductRepository _productRepository = new ProductRepository();
        public ActionResult Index()
        {
            var userId = User.Identity.GetUserId();

            var invoices = _invoiceRepository.GetInvoices(userId);

            return View(invoices);
        }

        public ActionResult Invoice(int id = 0)
        {
            var userId = User.Identity.GetUserId();

            var invoice = id == 0 ?
                GetNewInvoice(userId) :
                _invoiceRepository.GetInvoice(id, userId);

            var vm = PrepareInvoiceVm(invoice, userId);

            return View(vm);
        }

        private EditInvoiceViewModel PrepareInvoiceVm(
            Invoice invoice, string userId)
        {
            return new EditInvoiceViewModel
            {
                Invoice = invoice,
                Heading = invoice.Id == 0 ? "Dodawanie nowej faktury" : "Faktura",
                Clients = _clientRepository.GetClients(userId),
                MethodofPayment = _invoiceRepository.GetMethodsOfPayment(),
            };
        }

        private Invoice GetNewInvoice(string userId)
        {
            return new Invoice
            {
                UserId = userId,
                CreatedDate = DateTime.Now,
                PaymentDate = DateTime.Now.AddDays(7)
            };
        }

        public ActionResult InvoicePosition(
            int invoiceId, int InvoicePositionId = 0)
        {
            var userId = User.Identity.GetUserId();

            var invoicePosition = InvoicePositionId == 0 ?
                GetNewPosition(invoiceId, InvoicePositionId) :
                _invoiceRepository.GetInvoicePosition(InvoicePositionId, userId);

            var vm = PrepareInvoicePositionVm(invoicePosition);

            return View(vm);
        }

        private EditInvoicePositionViewModel PrepareInvoicePositionVm(InvoicePosition invoicePosition)
        {
            var userId = User.Identity.GetUserId();

            return new EditInvoicePositionViewModel
            {
                InvoicePosition = invoicePosition,
                Heading = invoicePosition.Id == 0 ? "Dodawanie nowej pozycji" : "Pozycja",
                Products = _productRepository.GetProducts(userId),
                UnitofMeasures = _invoiceRepository.GetUnitsofMeasures()

            };
        }

        private InvoicePosition GetNewPosition(
            int invoiceId, int invoicePositionId)
        {
            return new InvoicePosition
            {
                InvoiceId = invoiceId,
                Id = invoicePositionId, 
            };
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Invoice(Invoice invoice)
        {
            var userId = User.Identity.GetUserId();
            invoice.UserId = userId;

            if (!ModelState.IsValid)
            {
                var vm = PrepareInvoiceVm(invoice, userId);
                return View("Invoice", vm);
            }

            if (invoice.Id == 0)
                _invoiceRepository.Add(invoice);
            else
                _invoiceRepository.Update(invoice);

            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult InvoicePosition(InvoicePosition invoicePosition)
        {

            var userId = User.Identity.GetUserId();

            var product = _productRepository
                .GetProduct(invoicePosition.ProductId, userId);

            if (!ModelState.IsValid)
            {
                var vm = PrepareInvoicePositionVm(invoicePosition);
                return View("Invoice", vm);
            }
                                    
            invoicePosition.NetValue = invoicePosition.Quantity * product.NetPrice;

            invoicePosition.VatValue = invoicePosition.Quantity * product.VatAmount;

            if (invoicePosition.Id == 0)
                _invoiceRepository.AddPosition(invoicePosition, userId);
            else
                _invoiceRepository.UpdatePosition(invoicePosition, userId);

            _invoiceRepository.UpdateInvoiceNetValue(invoicePosition.InvoiceId, userId);
            _invoiceRepository.UpdateInvoiceGrossValue(invoicePosition.InvoiceId, userId);


            return RedirectToAction("Invoice",
                new { id = invoicePosition.InvoiceId });
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            try
            {
                var userId = User.Identity.GetUserId();
                _invoiceRepository.Delete(id, userId);
            }
            catch (Exception exception)
            {
                //logowanie
                return Json(new { Success = false, Message = exception.Message }); ;
            }


            return Json(new { Success = true });
        }

        [HttpPost]
        public ActionResult DeletePosition(int id, int invoiceId)
        {
            var invoiceNetValue = 0m;
            var invoiceGrossValue = 0m;


            try
            {
                var userId = User.Identity.GetUserId();
                _invoiceRepository.DeletePosition(id, userId);
                 invoiceNetValue = _invoiceRepository.UpdateInvoiceNetValue(invoiceId, userId);
                invoiceGrossValue = _invoiceRepository.UpdateInvoiceGrossValue(invoiceId, userId);
            }
            catch (Exception exception)
            {
                //logowanie
                return Json(new { Success = false, Message = exception.Message }); ;
            }


            return Json(new { Success = true, InvoiceNetValue = invoiceNetValue, InvoiceGrossValue = invoiceGrossValue });
        }

        
        [AllowAnonymous]
        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public ActionResult Product()
        {
            var userId = User.Identity.GetUserId();

            var products = _productRepository.GetProducts(userId);

            return View(products);
        }

        public ActionResult AddEditProduct(int id = 0)
        {
            var userId = User.Identity.GetUserId();

            var product = id == 0 ?
                GetNewProduct(userId) :
                _productRepository.GetProduct(id, userId);

            var pvm = PrepareProductVm(product, userId);

            return View(pvm);
        }

        private EditProductViewModel PrepareProductVm(
            Product product, string userId)
        {
            return new EditProductViewModel
            {
                Product = product,
                Heading = product.Id == 0 ? "Dodawanie nowego produktu" : "Produkt",
            };
        }

        private Product GetNewProduct(string userId)
        {
            return new Product
            {
                UserId = userId,
            };
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddEditProduct(Product product)
        {
            var userId = User.Identity.GetUserId();
            product.UserId = userId;

            if (!ModelState.IsValid)
            {
                var pvm = PrepareProductVm(product, userId);

                return View("AddEditProduct", pvm);
            }

            if (product.Id == 0)
                _productRepository.Add(product);
            else
                _productRepository.Update(product);

            return RedirectToAction("Product");
        }

        [HttpPost]
        public ActionResult DeleteProduct(int id)
        {
            try
            {
                var userId = User.Identity.GetUserId();
                _productRepository.Delete(id, userId);
            }
            catch (Exception exception)
            {
                //logowanie
                return Json(new { Success = false, Message = exception.Message }); ;
            }


            return Json(new { Success = true });
        }

        public ActionResult Client()
        {
            var userId = User.Identity.GetUserId();

            var clients = _clientRepository.GetClients(userId);

            return View(clients);
        }

        public ActionResult AddEditClient (int id = 0)
        {
            var userId = User.Identity.GetUserId();

            var client = id == 0 ?
                GetNewClient(userId) :
                _clientRepository.GetClient(id, userId);

            var cvm = PrepareClientVm(client, userId);

            return View(cvm);
        }

        private EditClientViewModel PrepareClientVm( Client client, string userId)
        {
            return new EditClientViewModel
            {
                Client = client,
                Heading = client.Id == 0 ? "Dodawanie nowego klienta" : "Klient",
            };
        }

        private Client GetNewClient(string userId)
        {
            return new Client
            {
                UserId = userId
            };
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddEditClient(Client client)
        {
            var userId = User.Identity.GetUserId();

            if (!ModelState.IsValid)
            {
                var cvm = PrepareClientVm(client, userId);

                return View("AddEditClient", cvm);
            }

            if (client.Id == 0)

InvoiceManager/Controllers/PrintController.cs
using InvoiceManager.Models.Domains;
using InvoiceManager.Models.Repositories;
using Microsoft.AspNet.Identity;
using Rotativa;
using Rotativa.Options;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace InvoiceManager.Controllers
{
    [Authorize]
    public class PrintController : Controller
    {
        private InvoiceRepository _invoiceRepository = new InvoiceRepository();

        public ActionResult InvoiceToPdf(int id)
        {
            var handle = Guid.NewGuid().ToString();
            var userId = User.Identity.GetUserId();
            var invoice = _invoiceRepository.GetInvoice(id, userId);

            TempData[handle] = GetPdfContent(invoice);

            return Json(new
            {
                FileGuid = handle,
                FileName = $@"Faktura_{invoice.Id}.pdf"
            });
        }

        private byte[] GetPdfContent(Invoice invoice)
        {
            var pdfResult = new ViewAsPdf(@"InvoiceTemplate", invoice)
            {
                PageSize = Size.A4,
                PageOrientation = Orientation.Portrait
            };

            return pdfResult.BuildFile(ControllerContext);
        }

        public ActionResult PrintInvoice(int id)
        {
            var userId = User.Identity.GetUserId();
            var invoice = _invoiceRepository.GetInvoice(id, userId);

            return View("InvoiceTemplate", invoice);
        }

        public ActionResult DownloadInvoicePdf(string fileGuid, string fileName)
        {
            if (TempData[fileGuid] == null)
                throw new Exception("Błąd przy próbie eksportu faktury do PDF.");

            var data = TempData[fileGuid] as byte[];
            return File(data, "application/pdf", fileName);
            
        }
    }
}

InvoiceManager/Views/Home/AddEditClient.cshtml
@model InvoiceManager.Models.ViewModels.EditClientViewModel

@{
    ViewBag.Title = Model.Heading;
}

<h2 class="mb-3">@Model.Heading</h2>
<div class="row">
    <div class="col-lg-6">
        @using (Html.BeginForm("AddEditClient", "Home"))
        {
            @Html.AntiForgeryToken()

            if (Model.Client.Id == 0)
            {
                <p class="alert alert-info mt-4 mb-4">
                    Wszystkie pola poza polem NIP są
                    <strong>wymagane</strong>
                </p>
            }

            @Html.HiddenFor(x => x.Client.Id)
            @Html.HiddenFor(x => x.Client.UserId)
            @Html.HiddenFor(x => x.Client.AddressId)

            <div class="form-group">
                @Html.LabelFor(x => x.Client.Name)
                @Html.TextBoxFor(x => x.Client.Name,
               new { @class = "form-control", autofocus = "autofocus" })
                @Html.ValidationMessageFor(x => x.Client.Name)
            </div>
            <div class="form-group">
                @Html.LabelFor(x => x.Client.Address.Nip)
                @Html.TextBoxFor(x => x.Client.Address.Nip,
               new { @class = "form-control" })
                @Html.ValidationMessageFor(x => x.Client.Address.Nip)
            </div>
            <div class="form-group">
                @Html.LabelFor(x => x.Client.Address.PostalCode)
                @Html.TextBoxFor(x => x.Client.Address.PostalCode,
               new { @class = "form-control" })
                @Html.ValidationMessageFor(x => x.Client.Address.PostalCode)
            </div>
            <div class="form-group">
                @Html.LabelFor(x => x.Client.Address.City)
                @Html.TextBoxFor(x => x.Client.Address.City,
               new { @class = "form-control" })
                @Html.ValidationMessageFor(x => x.Client.Address.City)
            </div>
            <div class="form-group">
                @Html.LabelFor(x => x.Client.Address.Street)
                @Html.TextBoxFor(x => x.Client.Address.Street,
               new { @class = "form-control" })
                @Html.ValidationMessageFor(x => x.Client.Address.Street)
            </div>
            <div class="form-group">
                @Html.LabelFor(x => x.Client.Address.Number)
                @Html.TextBoxFor(x => x.Client.Address.Number,
               new { @class = "form-control" })
                @Html.ValidationMessageFor(x => x.Client.Address.Number)
            </div>
            <div class="form-group">
                @Html.LabelFor(x => x.Client.Email)
                @Html.TextBoxFor(x => x.Client.Email,
               new { @class = "form-control" })
                @Html.ValidationMessageFor(x => x.Client.Email)
            </div>

            <button class="btn btn-primary btn-lg mt-2" type="submit">
                Zapisz
            </button>
        }
    </div>
</div>

InvoiceManager/Views/Home/AddEditProduct.cshtml
@model InvoiceManager.Models.ViewModels.EditProductViewModel
@{
    ViewBag.Title = Model.Heading;
}

<h2 class="mb-3">@Model.Heading</h2>
<div class="row">
    <div class="col-lg-6">
        @using (Html.BeginForm("AddEditProduct", "Home"))
        {
            @Html.AntiForgeryToken()

            if (Model.Product.Id == 0)
            {
                <p class="alert alert-info mt-4 mb-4">
                    Wszystkie pola są
                    <strong>wymagane</strong>
                </p>
            }

            @Html.HiddenFor(x => x.Product.Id)
            @Html.HiddenFor(x => x.Product.UserId)


            <div class="form-group">
                @Html.LabelFor(x => x.Product.Name)
                @Html.TextBoxFor(x => x.Product.Name,
                new { @class = "form-control", autofocus = "autofocus" })
                @Html.ValidationMessageFor(x => x.Product.Name)
            </div>

            <div class="form-group">
                @Html.LabelFor(x => x.Product.NetPrice)
                @Html.TextBoxFor(x => x.Product.NetPrice,
                new { @class = "form-control" })
                @Html.ValidationMessageFor(x => x.Product.NetPrice)
            </div>
            <div class="form-group">
                @Html.LabelFor(x => x.Product.VatRate)
                @Html.TextBoxFor(x => x.Product.VatRate,
                new { @class = "form-control" })
                @Html.ValidationMessageFor(x => x.Product.VatRate)
            </div>
            <div class="form-group">
                @Html.LabelFor(x => x.Product.VatAmount)
                @Html.TextBoxFor(x => x.Product.VatAmount,
                new { @class = "form-control", @readonly = "readonly" })
                @Html.ValidationMessageFor(x => x.Product.VatAmount)
            </div>
            <div class="form-group">
                @Html.LabelFor(x => x.Product.GrossPrice)
                @Html.TextBoxFor(x => x.Product.GrossPrice,
                new { @class = "form-control", @readonly = "readonly" })
                @Html.ValidationMessageFor(x => x.Product.GrossPrice)
            </div>

            <button class="btn btn-primary btn-lg mt-2" type="submit">
                Zapisz
            </button>
        }
    </div>
</div>

@section Scripts
{
    <script>
        $.validator.methods.range = function (value, element, param) {
            var globalizedValue = value.replace(".", ",");
            return this.optional(element) || (globalizedValue >= param[0] && globalizedValue <= param[1]);
        }

        $.validator.methods.number = function (value, element) {
            return this.optional(element) || /-?(?:\d+|\d{1,3}(?:[\s\.,]\d{3})+)(?:[\.,]\d+)?$/.test(value);
        }


        function calculate() {
            var netprice = parseFloat($('#Product_NetPrice').val().replace(",","."));
            var vatrate = parseFloat($('#Product_VatRate').val());

            var vatamount = netprice * vatrate / 100;
            var grossprice = netprice + vatamount;

            $('#Product_VatAmount').val(vatamount.toFixed(2).toString().replace(".", ","));
            $('#Product_GrossPrice').val(grossprice.toFixed(2).toString().replace(".", ","));
        }

        $(document).ready(function () {

            $('#Product_NetPrice').change(calculate);
            $('#Product_VatRate').change(calculate);
            $(vatamount).change(calculate);
            $(grossprice).change(calculate);

        });
    </script>
}

InvoiceManager/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Kontakt";
}
<h2>@ViewBag.Title.</h2>

<address>
    <strong>GitHub:</strong>   <a href="https://github.com/LukSt92">https://github.com/LukSt92</a>
</address>

InvoiceManager/Views/Home/Invoice.cshtml
@model InvoiceManager.Models.ViewModels.EditInvoiceViewModel
@{
    ViewBag.Title = Model.Heading;
}

<h2 class="mb-3">@Model.Heading</h2>

@if (Model.Invoice.Id != 0)
{
    <button class="btn btn-primary mb-3"
            onclick='window.location.href="@Url.Action("InvoicePosition", "Home", new { invoiceId = Model.Invoice.Id })"'>
        Dodaj pozycję
    </button>

    <button class="btn btn-secondary mb-3" onclick="generatePdf()">
        Generuj PDF
    </button>

    <button type="button" class="btn btn-warning mb-3" onclick="printInvoice()">
        Drukuj
    </button>
}

<div class="row">
    <div class="col-lg-3">
        @using (Html.BeginForm("Invoice", "Home"))
        {
            @Html.AntiForgeryToken()

            if (Model.Invoice.Id == 0)
            {
                <p class="alert alert-info mt-4 mb-4">
                    Pola tytuł, klient, sposób płatności i data płatności są
                    <strong>wymagane</strong>
                </p>
            }

            @Html.HiddenFor(x => x.Invoice.Id)
            @Html.HiddenFor(x => x.Invoice.UserId)


            <div class="form-group">
                @Html.LabelFor(x => x.Invoice.Title)
                @Html.TextBoxFor(x => x.Invoice.Title,
                new { @class = "form-control", autofocus = "autofocus" })
                @Html.ValidationMessageFor(x => x.Invoice.Title)
            </div>

            <div class="form-group">
                @Html.LabelFor(x => x.Invoice.ClientId)
                @Html.DropDownListFor(x => x.Invoice.ClientId,
                new SelectList(Model.Clients, "Id", "Name"),
                "-- Wybierz klienta --",
                new { @class = "form-control" })
                @Html.ValidationMessageFor(x => x.Invoice.ClientId)
            </div>

            if (Model.Invoice.Id != 0)
            {
                <div class="form-group">
                    @Html.LabelFor(x => x.Invoice.NetValue)
                    @Html.TextBoxFor(x => x.Invoice.NetValue, "{0:C}",
                    new { @class = "form-control", @readonly = "readonly" })
                </div>
                <div class="form-group">
                    @Html.LabelFor(x => x.Invoice.GrossValue)
                    @Html.TextBoxFor(x => x.Invoice.GrossValue, "{0:C}",
                    new { @class = "form-control", @readonly = "readonly" })
                </div>
            }
            <div class="form-group">
                @Html.LabelFor(x => x.Invoice.MethodOfPaymentId)
                @Html.DropDownListFor(x => x.Invoice.MethodOfPaymentId,
                new SelectList(Model.MethodofPayment, "Id", "Name"),
                "-- Wybierz sposób płatności --",
                new { @class = "form-control" })
                @Html.ValidationMessageFor(x => x.Invoice.MethodOfPaymentId)
            </div>

            <div class="form-group">
                @Html.LabelFor(x => x.Invoice.PaymentDate)
                @Html.TextBoxFor(x => x.Invoice.PaymentDate, "{0:dd-MM-yyyy}",
                new
                     {
                         @class = "form-control",
                    @id = "PaymentDate",
                    autocomplete = "off"
                     })
                @Html.ValidationMessageFor(x => x.Invoice.PaymentDate)
            </div>

            <div class="form-group">
                @Html.LabelFor(x => x.Invoice.Comments)
                @Html.TextAreaFor(x => x.Invoice.Comments,
                new { @class = "form-control" })
                @Html.ValidationMessageFor(x => x.Invoice.Comments)
            </div>

            <button class="btn btn-primary btn-lg mt-2" type="submit">
                Zapisz
            </button>

        }
    </div>
    <div class="col-8 offset-lg-1">
        @if (Model.Invoice.Id != 0)
        {
            @Html.Partial("_InvoicePosition", Model.Invoice.InvoicePositions)
        }
    </div>
</div>



@section Scripts
{
    <script type="text/javascript">

        function printInvoice() {
            var url = '@Url.Action("PrintInvoice", "Print")' +
                '?id=' + '@Model.Invoice.Id';

            var myWindow = window.open(url, '', 'width=800,height=600');
            myWindow.onload = function () {
                myWindow.print();
                myWindow.onafterprint = function () {
                    myWindow.close();
                };
            };
        }

        function generatePdf() {

            $.ajax({
            type: 'POST',
            url: "@Url.Action("InvoiceToPdf", "Print")",
                data: {
                id: '@Model.Invoice.Id'
            },
                success: function (data) {
                    window.location = '@Url.Action("DownloadInvoicePdf", "Print")'
                        + '?fileGuid=' + data.FileGuid + '&fileName=' + data.FileName;
            },
            error: function (data) {
                alert(data.Message);
            },
                dataType: 'json',
            cache: false
        });
        }

        function deleteInvoicePosition(id, invoiceId, btn) {
            if (!confirm("Czy na pewno chcesz usunąć pozycję?"))
                return;

            $.ajax({
            type: 'POST',
            url: "@Url.Action("DeletePosition", "Home")",
            data: {
                id: id,
                invoiceid: invoiceId
            },
            success: function (data) {
                if (data.Success) {
                    var row = btn.parentNode.parentNode;
                    row.parentNode.removeChild(row);

                    $('#Invoice_NetValue').val(data.InvoiceNetValue.toFixed(2).replace(".", ","));
                    $('#Invoice_GrossValue').val(data.InvoiceGrossValue.toFixed(2).replace(".", ","));

                } else {
                    alert(data.Message);
                }
            },
            error: function (data) {
                alert(data.Message);
            },
            dataType: 'json'
            });
        }

        $(document).ready(function () {

            $.validator.methods.number = function (value, element) {
                return this.optional(element) || /^-?(?:\d+|\d{1,3}(?:[\s\.,]\d{3})+)(?:[\.,]\d+)?$/.test(value);

            }

            $.validator.methods.date = function (value, element) {
                var isChrome = /Chrome/.test(navigator.userAgent) && /Google Inc/
                    .test(navigator.vendor);
                if (isChrome) {
                    var d = new Date();
                    return this.optional(element) || !/Invalid|NaN/.test(new Date(d.toLocaleDateString(value)));
                } else {
                    return this.optional(element) || !/Invalid|NaN/.test(new Date(value));
                }
            };

            $('#PaymentDate').datepicker({
                format: "dd-mm-yyyy",
                language: "pl",
                multidate: false,
                autoclose: true,
                todayHighlight: true,
                forceParse: false,
                startDate: "-10d"
            });

        });

    </script>
}